# Generated by Django 5.0.1 on 2024-03-21 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arconnectmanagerapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentitem",
            name="state",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
