# Generated by Django 5.0.1 on 2024-04-16 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arconnectmanagerapp", "0002_alter_tournamentitem_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentitem",
            name="players",
            field=models.ManyToManyField(
                related_name="players", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
