# Generated by Django 5.0.1 on 2024-04-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arconnectmanagerapp", "0003_tournamentitem_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentitem",
            name="challonge_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tournamentitem",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
