# Generated by Django 5.0.1 on 2024-04-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "arconnectmanagerapp",
            "0004_tournamentitem_challonge_id_tournamentitem_image_url",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournamentitem",
            old_name="image_url",
            new_name="challonge_image_url",
        ),
    ]
